# Generated by Django 2.1.1 on 2018-11-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0002_auto_20181104_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='URL страницы'),
        ),
    ]
