# Generated by Django 2.1.1 on 2019-01-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0004_auto_20190120_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
    ]
