# Generated by Django 2.1.1 on 2019-01-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0009_auto_20190120_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
    ]
