# Generated by Django 2.1.1 on 2019-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0013_auto_20190203_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Текст'),
        ),
    ]
