# Generated by Django 2.1.1 on 2019-02-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0014_auto_20190203_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='title',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Заголовок'),
        ),
    ]
