# Generated by Django 2.1.1 on 2019-02-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0015_auto_20190203_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
