# Generated by Django 2.1.1 on 2019-02-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0016_auto_20190203_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='title',
        ),
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
