# Generated by Django 2.1.1 on 2019-02-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0017_auto_20190203_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
