# Generated by Django 2.1.1 on 2019-02-18 21:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appquestions', '0018_auto_20190203_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='URL страницы'),
        ),
    ]
